start-at-login = true

after-startup-command = [
    'exec-and-forget borders active_color=0xff1A91E5 inactive_color=0xff494d64 width=7.0',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Automatic app placing
[[on-window-detected]]
if.app-name-regex-substring = 'calendar'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'brave'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'arc'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'dia'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'goland'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'zed'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'cursor'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'warp'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = ['move-node-to-workspace S']

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = ['move-node-to-workspace S']

[[on-window-detected]]
if.app-name-regex-substring = 'notion'
run = ['move-node-to-workspace N']

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = ['move-node-to-workspace N']

# MAIN bindings
[mode.main.binding]

# Change container layout AND direction.
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Move between apps in the same workspace.
ctrl-shift-h = 'focus left'
ctrl-shift-j = 'focus down'
ctrl-shift-k = 'focus up'
ctrl-shift-l = 'focus right'

# Move apps in the container AND change direction.
ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-j = 'move down'
ctrl-alt-shift-k = 'move up'
ctrl-alt-shift-l = 'move right'

# Resizing.
ctrl-shift-z = 'fullscreen'
ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

# Movements between workspaces.
alt-1 = 'workspace 1' # Calendar
alt-2 = 'workspace 2' # Browser
alt-3 = 'workspace 3' # Editors
alt-4 = 'workspace 4' # Terminal
alt-5 = 'workspace 5'
alt-n = 'workspace N' # Notes
alt-s = 'workspace S' # Social

# Move app to workspace.
ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-n = 'move-node-to-workspace N'
ctrl-shift-s = 'move-node-to-workspace S'

alt-shift-tab = 'move-node-to-monitor --wrap-around next'

# SERVICE bindings.
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # Reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
